# Generated by Django 5.2.2 on 2025-06-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tag_users_note_delete_readingnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='users',
            name='total_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='total_following',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='users',
            name='following',
        ),
        migrations.AddField(
            model_name='users',
            name='following',
            field=models.JSONField(default=list),
        ),
    ]
