# Generated by Django 5.2.2 on 2025-07-03 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_users_followers_users_total_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='book_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.users')),
            ],
        ),
    ]
