# Generated by Django 5.2.2 on 2025-07-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_book_id_alter_note_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
    ]
