# Generated by Django 5.2.2 on 2025-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='users',
            name='following',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follows', to='notes.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='notes.users'),
        ),
    ]
