# Generated by Django 5.2.2 on 2025-07-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_users_followers_remove_users_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=100),
        ),
    ]
